import { RttCall } from "../../../../../src/components/radio/rtts/types"
import { rttCallFactory } from "../../../../../tests/factories/radio/rtt"

const now = new Date()

export const mockEmergencyCall: RttCall = rttCallFactory.build({
  id: "rtt-call-001",
  callType: "Emergency",
  talkGroup: "TG-102",
  routeId: "66",
  routeName: "66",
  vehicleId: "2104",
  garage: "Cabot",
  receivedAt: new Date(now.getTime() - 2 * 60 * 1000),
  direction: "Outbound",
  variant: "Harvard via Allston",
  currentLocation: "Harvard Ave @ Commonwealth Ave",
  operatorBadge: "54321",
  operatorName: "J. Doe",
  runNumber: "R-104",
  status: "unassigned",
  respondedBy: null,
  answeredAt: null,
})

export const mockPrttCall: RttCall = rttCallFactory.build({
  id: "rtt-call-002",
  callType: "PRTT",
  talkGroup: "TG-105",
  routeId: "39",
  routeName: "39",
  vehicleId: "1845",
  garage: "Southampton",
  receivedAt: new Date(now.getTime() - 5 * 60 * 1000),
  direction: "Inbound",
  variant: "Forest Hills - Back Bay Station",
  currentLocation: "Huntington Ave @ Longwood Ave",
  operatorBadge: "48291",
  operatorName: "M. Garcia",
  runNumber: "R-039",
  status: "unassigned",
  respondedBy: null,
  answeredAt: null,
})

export const mockActivePrttCallByOther: RttCall = rttCallFactory.build({
  id: "rtt-call-003",
  callType: "PRTT",
  talkGroup: "TG-101",
  routeId: "1",
  routeName: "1",
  vehicleId: "1290",
  garage: "Southampton",
  receivedAt: new Date(now.getTime() - 7 * 60 * 1000),
  direction: "Outbound",
  variant: "Harvard - Nubian Station",
  currentLocation: "Mass Ave @ Beacon St",
  operatorBadge: "50122",
  operatorName: "T. Vance",
  runNumber: "R-001",
  status: "active",
  respondedBy: "Sarah Connor",
  answeredAt: new Date(now.getTime() - 4 * 60 * 1000),
})

export const mockStandardRttCall1: RttCall = rttCallFactory.build({
  id: "rtt-call-004",
  callType: "RTT",
  talkGroup: "TG-104",
  routeId: "57",
  routeName: "57",
  vehicleId: "1932",
  garage: "Cabot",
  receivedAt: new Date(now.getTime() - 10 * 60 * 1000),
  direction: "Inbound",
  variant: "Watertown Yard - Kenmore",
  currentLocation: "Commonwealth Ave @ Warren St",
  operatorBadge: "39481",
  operatorName: "K. Patel",
  runNumber: "R-057",
  status: "unassigned",
  respondedBy: null,
  answeredAt: null,
})

export const mockStandardRttCall2: RttCall = rttCallFactory.build({
  id: "rtt-call-005",
  callType: "RTT",
  talkGroup: "TG-108",
  routeId: "111",
  routeName: "111",
  vehicleId: "2055",
  garage: "Charlestown",
  receivedAt: new Date(now.getTime() - 12 * 60 * 1000),
  direction: "Outbound",
  variant: "Woodlawn - Haymarket",
  currentLocation: "Broadway @ Chelsea St",
  operatorBadge: "41902",
  operatorName: "L. Martinez",
  runNumber: "R-111",
  status: "unassigned",
  respondedBy: null,
  answeredAt: null,
})

export const mockIncomingCalls: RttCall[] = [
  mockEmergencyCall,
  mockPrttCall,
  mockActivePrttCallByOther,
  mockStandardRttCall1,
  mockStandardRttCall2,
]

export const mockPastCall1: RttCall = rttCallFactory.build({
  id: "rtt-past-001",
  callType: "RTT",
  talkGroup: "TG-102",
  routeId: "28",
  routeName: "28",
  vehicleId: "1750",
  garage: "Cabot",
  receivedAt: new Date(now.getTime() - 45 * 60 * 1000),
  direction: "Inbound",
  variant: "Mattapan - Ruggles",
  currentLocation: "Blue Hill Ave @ Warren St",
  operatorBadge: "52199",
  operatorName: "A. Jackson",
  runNumber: "R-028",
  status: "done",
  respondedBy: "Dispatcher Smith",
  answeredAt: new Date(now.getTime() - 43 * 60 * 1000),
  markedDoneAt: new Date(now.getTime() - 38 * 60 * 1000),
})

export const mockPastCall2: RttCall = rttCallFactory.build({
  id: "rtt-past-002",
  callType: "PRTT",
  talkGroup: "TG-104",
  routeId: "77",
  routeName: "77",
  vehicleId: "1622",
  garage: "Charlestown",
  receivedAt: new Date(now.getTime() - 85 * 60 * 1000),
  direction: "Outbound",
  variant: "Arlington Heights - Harvard",
  currentLocation: "Massachusetts Ave @ Appleton St",
  operatorBadge: "49001",
  operatorName: "B. Nguyen",
  runNumber: "R-077",
  status: "done",
  respondedBy: "Dispatcher Jones",
  answeredAt: new Date(now.getTime() - 83 * 60 * 1000),
  markedDoneAt: new Date(now.getTime() - 75 * 60 * 1000),
})

export const mockPastCall3: RttCall = rttCallFactory.build({
  id: "rtt-past-003",
  callType: "Emergency",
  talkGroup: "TG-101",
  routeId: "9",
  routeName: "9",
  vehicleId: "2201",
  garage: "Southampton",
  receivedAt: new Date(now.getTime() - 120 * 60 * 1000),
  direction: "Inbound",
  variant: "City Point - Copley via Broadway",
  currentLocation: "East Broadway @ L St",
  operatorBadge: "53210",
  operatorName: "D. Miller",
  runNumber: "R-009",
  status: "done",
  respondedBy: "Dispatcher Smith",
  answeredAt: new Date(now.getTime() - 119 * 60 * 1000),
  markedDoneAt: new Date(now.getTime() - 105 * 60 * 1000),
})

export const mockPastCalls: RttCall[] = [
  mockPastCall1,
  mockPastCall2,
  mockPastCall3,
]
