import { RttCall } from "../../../../../src/components/radio/rtts/types"
import { rttCallFactory } from "../../../../../tests/factories/radio/rtt"

const now = new Date()

export const mockEmergencyCall: RttCall = rttCallFactory.build({
  id: "rtt-call-001",
  callType: "Emergency",
  talkGroup: "TG-102",
  routeId: "66",
  routeName: "66",
  vehicleId: "2098",
  garage: "Cabot",
  receivedAt: new Date(now.getTime() - 2 * 60 * 1000),
  direction: "Outbound",
  variant: "66_9 Harvard via Allston",
  currentLocation: "23 Hawes St, Cambridge MA. 02140",
  operatorBadge: "891491",
  operatorName: "Shania Twain",
  runNumber: "123-0981",
  adherence: "7 min late",
  status: "unassigned",
  respondedBy: null,
  answeredAt: null,
})

export const mockActivePrttCallByOther: RttCall = rttCallFactory.build({
  id: "rtt-call-002",
  callType: "PRTT",
  talkGroup: "TG-101",
  routeId: "88",
  routeName: "88",
  vehicleId: "2345",
  garage: "Charlestown",
  receivedAt: new Date(now.getTime() - 4 * 60 * 1000),
  direction: "Outbound",
  variant: "88 Lechmere",
  currentLocation: "23 Hawes St, Cambridge MA. 02140",
  operatorBadge: "10283",
  operatorName: "Cassandra Bullock",
  runNumber: "124-3923",
  adherence: "23 min late",
  status: "active",
  respondedBy: "T. Bridges",
  answeredAt: new Date(now.getTime() - 2 * 60 * 1000),
})

export const mockPrttCall: RttCall = rttCallFactory.build({
  id: "rtt-call-003",
  callType: "PRTT",
  talkGroup: "TG-105",
  routeId: "70",
  routeName: "70",
  vehicleId: "1895",
  garage: "Albany",
  receivedAt: new Date(now.getTime() - 6 * 60 * 1000),
  direction: "Inbound",
  variant: "70 Waltham - Central Square",
  currentLocation: "Main St @ Moody St",
  operatorBadge: "48291",
  operatorName: "M. Garcia",
  runNumber: "R-070",
  adherence: "On time",
  status: "unassigned",
  respondedBy: null,
  answeredAt: null,
})

export const mockStandardRttCall1: RttCall = rttCallFactory.build({
  id: "rtt-call-004",
  callType: "RTT",
  talkGroup: "TG-104",
  routeId: "1",
  routeName: "1",
  vehicleId: "1902",
  garage: "Cabot",
  receivedAt: new Date(now.getTime() - 8 * 60 * 1000),
  direction: "Inbound",
  variant: "1 Harvard - Nubian",
  currentLocation: "Massachusetts Ave @ Beacon St",
  operatorBadge: "39481",
  operatorName: "K. Patel",
  runNumber: "R-001",
  adherence: "4 min late",
  status: "unassigned",
  respondedBy: null,
  answeredAt: null,
})

export const mockStandardRttCall2: RttCall = rttCallFactory.build({
  id: "rtt-call-005",
  callType: "RTT",
  talkGroup: "TG-108",
  routeId: "111",
  routeName: "111",
  vehicleId: "2055",
  garage: "Charlestown",
  receivedAt: new Date(now.getTime() - 12 * 60 * 1000),
  direction: "Outbound",
  variant: "111 Woodlawn - Haymarket",
  currentLocation: "Broadway @ Chelsea St",
  operatorBadge: "41902",
  operatorName: "L. Martinez",
  runNumber: "R-111",
  adherence: "On time",
  status: "unassigned",
  respondedBy: null,
  answeredAt: null,
})

export const mockIncomingCalls: RttCall[] = [
  mockEmergencyCall,
  mockActivePrttCallByOther,
  mockPrttCall,
  mockStandardRttCall1,
  mockStandardRttCall2,
]

export const mockPastCall1: RttCall = rttCallFactory.build({
  id: "rtt-past-001",
  callType: "RTT",
  talkGroup: "TG-102",
  routeId: "66",
  routeName: "66",
  vehicleId: "2098",
  garage: "Cabot",
  receivedAt: new Date(now.getTime() - 45 * 60 * 1000),
  direction: "Outbound",
  variant: "66_9 Harvard via Allston",
  currentLocation: "23 Hawes St, Cambridge MA. 02140",
  operatorBadge: "891491",
  operatorName: "Shania Twain",
  runNumber: "123-0981",
  adherence: "7 min late",
  status: "done",
  respondedBy: "Dispatcher Smith",
  answeredAt: new Date(now.getTime() - 43 * 60 * 1000),
  markedDoneAt: new Date(now.getTime() - 38 * 60 * 1000),
})

export const mockPastCall2: RttCall = rttCallFactory.build({
  id: "rtt-past-002",
  callType: "PRTT",
  talkGroup: "TG-104",
  routeId: "77",
  routeName: "77",
  vehicleId: "1622",
  garage: "Charlestown",
  receivedAt: new Date(now.getTime() - 85 * 60 * 1000),
  direction: "Outbound",
  variant: "77 Arlington Heights - Harvard",
  currentLocation: "Massachusetts Ave @ Appleton St",
  operatorBadge: "49001",
  operatorName: "B. Nguyen",
  runNumber: "R-077",
  adherence: "On time",
  status: "done",
  respondedBy: "Dispatcher Jones",
  answeredAt: new Date(now.getTime() - 83 * 60 * 1000),
  markedDoneAt: new Date(now.getTime() - 75 * 60 * 1000),
})

export const mockPastCall3: RttCall = rttCallFactory.build({
  id: "rtt-past-003",
  callType: "Emergency",
  talkGroup: "TG-101",
  routeId: "9",
  routeName: "9",
  vehicleId: "2201",
  garage: "Southampton",
  receivedAt: new Date(now.getTime() - 120 * 60 * 1000),
  direction: "Inbound",
  variant: "9 City Point - Copley via Broadway",
  currentLocation: "East Broadway @ L St",
  operatorBadge: "53210",
  operatorName: "D. Miller",
  runNumber: "R-009",
  adherence: "15 min late",
  status: "done",
  respondedBy: "Dispatcher Smith",
  answeredAt: new Date(now.getTime() - 119 * 60 * 1000),
  markedDoneAt: new Date(now.getTime() - 105 * 60 * 1000),
})

export const mockPastCalls: RttCall[] = [
  mockPastCall1,
  mockPastCall2,
  mockPastCall3,
]
