name: Asana integration for GitHub PRs
on:
  workflow_dispatch:
  pull_request:
    types: [review_requested, closed, opened, reopened, converted_to_draft, edited, ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  call-workflow:
    permissions:
      # Deliberately assign no permissions to suppress the zizmor warning 
      # 'warning[excessive-permissions]'. The referenced reusable workflow (and
      # all its underlying components) only access the following information: 
      # 
      #  - GitHub Actions event payload
      #  - GitHub Actions workflow inputs and secrets
      # 
      # None of these require any of the default permissions.
      #
      # References
      # * https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#defining-access-for-the-github_token-scopes
      {}
    # Git ref points to latest commit on branch 'main'
    uses: mbta/workflows/.github/workflows/asana.yml@ead2d40fcc0c546bd6f099a6d8fcd9f9950eab03
    with:
      development-section: "✏️ In Progress"
      review-section: "👀 In Review"
      merged-section: "🚀 Ready to Deploy"
      trigger-phrase: "Asana Ticket.*:"
      attach-pr: true
    secrets:
      asana-token: ${{ secrets.ASANA_PERSONAL_ACCESS_TOKEN }}
      github-secret: ${{ secrets.ASANA_GITHUB_INTEGRATION_SECRET }}
