name: CI ❘ Zizmor

on:
  # Check proposed changes
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/*.yml'
  # Check pushed changes
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/*.yml'

permissions:
  {} # Deliberately assign no default permissions.


# https://docs.zizmor.sh/integrations/#via-zizmorcorezizmor-action
jobs:
  zizmor:
    name: Run zizmor 🌈
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
      contents: read         # Only needed for private repos. Needed to clone the repo.
      actions: read          # Only needed for private repos. Needed for upload-sarif to read workflow run info.
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
