name: Deploy to Prod (ECS)

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  deploy:
    permissions:
      # Required by GitHub Actions reusable workflow `./github/workflows/deploy-base.yml'
      id-token: write
      contents: read
    name: Deploy to Prod (ECS)
    uses: ./.github/workflows/deploy-base.yml
    with:
      env: prod
    secrets: inherit
