name: Deploy to Dev-green (ECS)

on:
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
      - labeled

jobs:
  deploy:
    name: Deploy to Dev-green (ECS)
    concurrency:
      group: dev-green
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'deploy-to-dev-green') }}
    uses: ./.github/workflows/deploy-base.yml
    with:
      env: dev-green
    secrets: inherit
