on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: true
      DOCKER_REPO:
        required: true
      SENTRY_AUTH_TOKEN:
        required: true
      SENTRY_ORG:
        required: true
      SENTRY_PROJECT:
        required: true
      SLACK_WEBHOOK:
        required: true


jobs:
  build:
    name: Build/push Docker Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      docker-tag-suffix: ${{ steps.build-push.outputs.docker-tag-suffix }}
      sentry-release: ${{ steps.version-ids.outputs.sentry-release }}
    steps:
      # Git ref points to release tag 'v4'
      - uses: actions/checkout@b6849436894e144dbce29d7d7fda2ae3bf9d8365
        with:
          persist-credentials: false
      - name: Get version ids
        id: version-ids
        run: |
          sanitized="$(tr '/' '-' <<< "${GITHUB_REF}_${GITHUB_SHA}")"
          echo "sentry-release=${sanitized}" >> "$GITHUB_OUTPUT"
      # Git ref points to release tag 'v2'
      - uses: mbta/actions/build-push-ecr@6cff1d5eef7e0d780190353278bc84fdf6177dab
        id: build-push
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          docker-repo: ${{ secrets.DOCKER_REPO }}
          docker-additional-args: --build-arg SENTRY_RELEASE=${{steps.version-ids.outputs.sentry-release}}
      - name: Upload static assets to S3
        run: bash upload_assets.sh "${DOCKER_TAG}" "${SENTRY_RELEASE}"
        env:
          DOCKER_TAG: ${{ steps.build-push.outputs.docker-tag }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_RELEASE: ${{ steps.version-ids.outputs.sentry-release }}


  deploy_ecs:
    name: Deploy (ECS)
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    environment: ${{ inputs.env }}
    concurrency:
      group: ${{ inputs.env }}
    env:
      ECS_CLUSTER: skate
      ECS_SERVICE: skate-${{ inputs.env }}
    steps:
      # Git ref points to release tag 'v2'
      - uses: mbta/actions/build-push-ecr@6cff1d5eef7e0d780190353278bc84fdf6177dab
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          ecs-cluster: ${{ env.ECS_CLUSTER }}
          ecs-service: ${{ env.ECS_SERVICE }}
          docker-tag: ${{ secrets.DOCKER_REPO }}:${{ needs.build.outputs.docker-tag-suffix }}
      # Git ref points to release tag 'v4'
      - uses: actions/checkout@b6849436894e144dbce29d7d7fda2ae3bf9d8365
        with:
          fetch-depth: 0
          persist-credentials: false
      # Git ref points to release tag 'v1'
      - uses: getsentry/action-release@a74facf8a080ecbdf1cb355f16743530d712abb7
        env:
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        with:
          environment: ${{ inputs.env }}
          version: ${{needs.build.outputs.sentry-release}}
          ignore_missing: true
      # Git ref points to release tag 'v2'
      - uses: mbta/actions/notify-slack-deploy@6cff1d5eef7e0d780190353278bc84fdf6177dab
        if: ${{ !cancelled() }}
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          job-status: ${{ job.status }}
